import { lazy, type LazyExoticComponent, type ComponentType } from "react"

export type Category = "text" | "developer" | "converter" | "generator" | "encoding" | "pdf" | "image" | "calculator" | "utility"

export interface ToolMeta {
  id: string
  name: string
  description: string
  category: Category
  icon: string
  keywords: string[]
  component: LazyExoticComponent<ComponentType>
}

export const categories: Record<Category, { label: string; color: string }> = {
  text:       { label: "Text Tools",          color: "cat-text" },
  developer:  { label: "Developer Tools",     color: "cat-developer" },
  converter:  { label: "Converters",          color: "cat-converter" },
  generator:  { label: "Generators",          color: "cat-generator" },
  encoding:   { label: "Encoding & Security", color: "cat-encoding" },
  pdf:        { label: "PDF Tools",           color: "cat-pdf" },
  image:      { label: "Image Tools",         color: "cat-image" },
  calculator: { label: "Calculators",         color: "cat-calculator" },
  utility:    { label: "Utilities",           color: "cat-utility" },
}

export const tools: ToolMeta[] = [
  // ── Text Tools ───────────────────────────────────────────────────────────
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count characters, words, sentences, and paragraphs with reading time",
    category: "text",
    icon: "FileText",
    keywords: ["count", "characters", "words", "sentences", "reading time"],
    component: lazy(() => import("@/tools/text/word-counter")),
  },
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text between UPPER, lower, Title, camelCase, snake_case, kebab-case",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["uppercase", "lowercase", "camel", "snake", "kebab", "title"],
    component: lazy(() => import("@/tools/text/case-converter")),
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text by paragraphs, sentences, or words",
    category: "text",
    icon: "Text",
    keywords: ["placeholder", "dummy", "text", "lorem"],
    component: lazy(() => import("@/tools/text/lorem-ipsum-generator")),
  },
  {
    id: "text-diff",
    name: "Text Diff",
    description: "Compare two texts side-by-side with highlighted differences",
    category: "text",
    icon: "GitCompare",
    keywords: ["compare", "difference", "diff", "merge"],
    component: lazy(() => import("@/tools/text/text-diff")),
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Live markdown editor with rendered preview",
    category: "text",
    icon: "BookOpen",
    keywords: ["markdown", "md", "preview", "editor"],
    component: lazy(() => import("@/tools/text/markdown-preview")),
  },
  {
    id: "string-encoder",
    name: "String Encoder/Decoder",
    description: "URL encode, HTML entities, and Unicode escape sequences",
    category: "text",
    icon: "Code",
    keywords: ["url", "encode", "decode", "html", "unicode", "escape"],
    component: lazy(() => import("@/tools/text/string-encoder")),
  },
  {
    id: "ascii-art-generator",
    name: "ASCII Art Generator",
    description: "Convert text into ASCII art with different styles.",
    category: "text",
    icon: "Terminal",
    keywords: ["ascii", "art", "text", "banner"],
    component: lazy(() => import("@/tools/text/ascii-art-generator")),
  },
  {
    id: "binary-translator",
    name: "Binary Translator",
    description: "Convert text to binary (0s and 1s) and back to readable text.",
    category: "text",
    icon: "Binary",
    keywords: ["binary", "translator", "01", "decode"],
    component: lazy(() => import("@/tools/text/binary-translator")),
  },
  {
    id: "bionic-reading",
    name: "Bionic Reading Converter",
    description: "Bold the first half of each word to guide your eyes for faster reading.",
    category: "text",
    icon: "Eye",
    keywords: ["bionic", "reading", "fast", "speed"],
    component: lazy(() => import("@/tools/text/bionic-reading")),
  },
  {
    id: "emoji-picker",
    name: "Emoji Picker",
    description: "Browse and copy emojis from any category.",
    category: "text",
    icon: "Smile",
    keywords: ["emoji", "picker", "copy", "icon"],
    component: lazy(() => import("@/tools/text/emoji-picker")),
  },
  {
    id: "find-replace",
    name: "Find and Replace",
    description: "Find text patterns and replace them — supports plain text and regex.",
    category: "text",
    icon: "Search",
    keywords: ["find", "replace", "regex", "text"],
    component: lazy(() => import("@/tools/text/find-replace")),
  },
  {
    id: "list-alphabetizer",
    name: "List Alphabetizer",
    description: "Sort any list of lines alphabetically in ascending or descending order.",
    category: "text",
    icon: "SortAsc",
    keywords: ["sort", "list", "alphabetical", "order"],
    component: lazy(() => import("@/tools/text/list-alphabetizer")),
  },
  {
    id: "morse-code",
    name: "Morse Code Converter",
    description: "Convert text to Morse code and back. Use / to separate words when decoding.",
    category: "text",
    icon: "Dot",
    keywords: ["morse", "code", "telegraph", "convert"],
    component: lazy(() => import("@/tools/text/morse-code")),
  },
  {
    id: "remove-duplicates",
    name: "Remove Duplicate Lines",
    description: "Remove repeated lines from any list or text block instantly.",
    category: "text",
    icon: "CopyMinus",
    keywords: ["remove", "duplicates", "unique", "lines"],
    component: lazy(() => import("@/tools/text/remove-duplicates")),
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    description: "Convert text into a clean URL slug for SEO-friendly links.",
    category: "text",
    icon: "Link",
    keywords: ["slug", "url", "seo", "clean"],
    component: lazy(() => import("@/tools/text/slug-generator")),
  },
  {
    id: "speech-to-text",
    name: "Speech to Text",
    description: "Speak and convert your voice to text using your browser's speech recognition.",
    category: "text",
    icon: "Mic",
    keywords: ["speech", "voice", "recognition", "dictate"],
    component: lazy(() => import("@/tools/text/speech-to-text")),
  },
  {
    id: "text-cleaner",
    name: "Text Cleaner",
    description: "Remove extra whitespace, blank lines, special characters, and more.",
    category: "text",
    icon: "Eraser",
    keywords: ["clean", "whitespace", "format", "text"],
    component: lazy(() => import("@/tools/text/text-cleaner")),
  },
  {
    id: "text-to-speech",
    name: "Text to Speech",
    description: "Convert text to spoken audio using your browser's built-in speech engine.",
    category: "text",
    icon: "Volume2",
    keywords: ["speech", "audio", "read", "aloud"],
    component: lazy(() => import("@/tools/text/text-to-speech")),
  },
  {
    id: "upside-down-text",
    name: "Upside Down Text Generator",
    description: "Flip your text upside down using Unicode characters.",
    category: "text",
    icon: "RotateCw",
    keywords: ["flip", "upside", "down", "unicode"],
    component: lazy(() => import("@/tools/text/upside-down-text")),
  },

  // ── Developer Tools ──────────────────────────────────────────────────────
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON with error highlighting",
    category: "developer",
    icon: "Braces",
    keywords: ["json", "format", "validate", "minify", "beautify"],
    component: lazy(() => import("@/tools/developer/json-formatter")),
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regex patterns with match highlighting and cheat sheet",
    category: "developer",
    icon: "Regex",
    keywords: ["regex", "regular expression", "pattern", "match", "test"],
    component: lazy(() => import("@/tools/developer/regex-tester")),
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode text or files to and from Base64",
    category: "developer",
    icon: "Binary",
    keywords: ["base64", "encode", "decode", "binary"],
    component: lazy(() => import("@/tools/developer/base64-encoder")),
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JWT tokens — header, payload, and expiry",
    category: "developer",
    icon: "Key",
    keywords: ["jwt", "token", "decode", "json web token", "auth"],
    component: lazy(() => import("@/tools/developer/jwt-decoder")),
  },
  {
    id: "code-minifier",
    name: "Code Minifier",
    description: "Minify HTML, CSS, and JavaScript code",
    category: "developer",
    icon: "Minimize2",
    keywords: ["minify", "compress", "html", "css", "javascript"],
    component: lazy(() => import("@/tools/developer/code-minifier")),
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries",
    category: "developer",
    icon: "Database",
    keywords: ["sql", "format", "query", "beautify", "database"],
    component: lazy(() => import("@/tools/developer/sql-formatter")),
  },
  {
    id: "box-shadow-generator",
    name: "Box Shadow Generator",
    description: "Visually build CSS box-shadow values with live preview.",
    category: "developer",
    icon: "Square",
    keywords: ["shadow", "css", "box", "style"],
    component: lazy(() => import("@/tools/developer/box-shadow-generator")),
  },
  {
    id: "color-contrast-checker",
    name: "Color Contrast Checker",
    description: "Check WCAG AA/AAA accessibility contrast ratios between two colors.",
    category: "developer",
    icon: "Contrast",
    keywords: ["contrast", "wcag", "accessibility", "color"],
    component: lazy(() => import("@/tools/developer/color-contrast-checker")),
  },
  {
    id: "robots-txt-generator",
    name: "Robots.txt Generator",
    description: "Generate a valid robots.txt file for your website's SEO crawling rules.",
    category: "developer",
    icon: "Bot",
    keywords: ["robots", "seo", "crawl", "txt"],
    component: lazy(() => import("@/tools/developer/robots-txt-generator")),
  },
  {
    id: "sitemap-generator",
    name: "Sitemap Generator",
    description: "Generate an XML sitemap for better search engine crawling and indexing.",
    category: "developer",
    icon: "Map",
    keywords: ["sitemap", "xml", "seo", "index"],
    component: lazy(() => import("@/tools/developer/sitemap-generator")),
  },
  {
    id: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode special characters for URLs or decode percent-encoded strings.",
    category: "developer",
    icon: "Link2",
    keywords: ["url", "encode", "decode", "percent"],
    component: lazy(() => import("@/tools/developer/url-encoder")),
  },

  // ── Converters ───────────────────────────────────────────────────────────
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert between HEX, RGB, and HSL with a color picker",
    category: "converter",
    icon: "Palette",
    keywords: ["color", "hex", "rgb", "hsl", "picker", "convert"],
    component: lazy(() => import("@/tools/converter/color-converter")),
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert length, weight, temperature, speed, and data storage",
    category: "converter",
    icon: "ArrowLeftRight",
    keywords: ["unit", "length", "weight", "temperature", "convert"],
    component: lazy(() => import("@/tools/converter/unit-converter")),
  },
  {
    id: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert between binary, octal, decimal, and hexadecimal",
    category: "converter",
    icon: "Hash",
    keywords: ["binary", "octal", "decimal", "hex", "base", "number"],
    component: lazy(() => import("@/tools/converter/number-base-converter")),
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert Unix timestamps to and from human-readable dates",
    category: "converter",
    icon: "Clock",
    keywords: ["timestamp", "unix", "epoch", "date", "time"],
    component: lazy(() => import("@/tools/converter/timestamp-converter")),
  },
  {
    id: "css-unit-converter",
    name: "CSS Unit Converter",
    description: "Convert between px, rem, em, vh, and vw",
    category: "converter",
    icon: "Ruler",
    keywords: ["css", "px", "rem", "em", "vh", "vw", "unit"],
    component: lazy(() => import("@/tools/converter/css-unit-converter")),
  },

  // ── Generators ───────────────────────────────────────────────────────────
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure passwords with configurable length and strength meter",
    category: "generator",
    icon: "Lock",
    keywords: ["password", "generate", "secure", "random", "strength"],
    component: lazy(() => import("@/tools/generator/password-generator")),
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate v4 UUIDs in bulk with one-click copy",
    category: "generator",
    icon: "Fingerprint",
    keywords: ["uuid", "guid", "unique", "id", "generate"],
    component: lazy(() => import("@/tools/generator/uuid-generator")),
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes",
    category: "generator",
    icon: "ShieldCheck",
    keywords: ["hash", "md5", "sha", "sha256", "checksum"],
    component: lazy(() => import("@/tools/generator/hash-generator")),
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from text or URLs with download",
    category: "generator",
    icon: "QrCode",
    keywords: ["qr", "qr code", "barcode", "generate"],
    component: lazy(() => import("@/tools/generator/qr-code-generator")),
  },
  {
    id: "gradient-generator",
    name: "Gradient Generator",
    description: "Build CSS gradients with a visual preview and copy code",
    category: "generator",
    icon: "Blend",
    keywords: ["gradient", "css", "linear", "radial", "color"],
    component: lazy(() => import("@/tools/generator/gradient-generator")),
  },
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate barcodes in EAN, Code 128, UPC, and other standard formats.",
    category: "generator",
    icon: "Barcode",
    keywords: ["barcode", "ean", "upc", "code128"],
    component: lazy(() => import("@/tools/generator/barcode-generator")),
  },
  {
    id: "dummy-image-placeholder",
    name: "Dummy Image Placeholder",
    description: "Generate placeholder images with custom dimensions, colors, and labels.",
    category: "generator",
    icon: "ImagePlay",
    keywords: ["placeholder", "image", "dummy", "lorem"],
    component: lazy(() => import("@/tools/generator/dummy-image-placeholder")),
  },
  {
    id: "email-signature-generator",
    name: "Email Signature Generator",
    description: "Create a professional HTML email signature in seconds.",
    category: "generator",
    icon: "Mail",
    keywords: ["email", "signature", "html", "branding"],
    component: lazy(() => import("@/tools/generator/email-signature-generator")),
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Create a custom favicon/app icon with text, color, and shape options.",
    category: "generator",
    icon: "Layout",
    keywords: ["favicon", "icon", "app", "web"],
    component: lazy(() => import("@/tools/generator/favicon-generator")),
  },
  {
    id: "privacy-policy-generator",
    name: "Privacy Policy Generator",
    description: "Generate a basic privacy policy for your website in seconds.",
    category: "generator",
    icon: "ShieldAlert",
    keywords: ["privacy", "policy", "legal", "gdpr"],
    component: lazy(() => import("@/tools/generator/privacy-policy-generator")),
  },
  {
    id: "terms-generator",
    name: "Terms & Conditions Generator",
    description: "Generate basic terms and conditions for your website or app.",
    category: "generator",
    icon: "FileWarning",
    keywords: ["terms", "conditions", "legal", "agreement"],
    component: lazy(() => import("@/tools/generator/terms-generator")),
  },

  // ── Encoding & Security ──────────────────────────────────────────────────
  {
    id: "html-entity-encoder",
    name: "HTML Entity Encoder",
    description: "Encode and decode HTML entities for XSS prevention",
    category: "encoding",
    icon: "Shield",
    keywords: ["html", "entity", "encode", "decode", "xss", "security"],
    component: lazy(() => import("@/tools/encoding/html-entity-encoder")),
  },
  {
    id: "checksum-verifier",
    name: "Checksum Verifier",
    description: "Verify file integrity via MD5 and SHA checksums",
    category: "encoding",
    icon: "FileCheck",
    keywords: ["checksum", "verify", "integrity", "md5", "sha", "file"],
    component: lazy(() => import("@/tools/encoding/checksum-verifier")),
  },

  // ── PDF Tools ────────────────────────────────────────────────────────────
  {
    id: "pdf-merger",
    name: "PDF Merger",
    description: "Combine multiple PDF files into one document — reorder before merging",
    category: "pdf",
    icon: "FilePlus2",
    keywords: ["pdf", "merge", "combine", "join", "concatenate"],
    component: lazy(() => import("@/tools/pdf/pdf-merger")),
  },
  {
    id: "pdf-splitter",
    name: "PDF Splitter",
    description: "Extract specific pages or page ranges from a PDF into a new file",
    category: "pdf",
    icon: "Scissors",
    keywords: ["pdf", "split", "extract", "pages", "separate"],
    component: lazy(() => import("@/tools/pdf/pdf-splitter")),
  },
  {
    id: "pdf-metadata",
    name: "PDF Metadata Viewer",
    description: "Inspect PDF properties — author, page count, creation date, and more",
    category: "pdf",
    icon: "FileSearch",
    keywords: ["pdf", "metadata", "info", "author", "title", "properties"],
    component: lazy(() => import("@/tools/pdf/pdf-metadata")),
  },

  // ── Image Tools ──────────────────────────────────────────────────────────
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize images to exact pixel dimensions with aspect-ratio lock",
    category: "image",
    icon: "Scaling",
    keywords: ["image", "resize", "dimensions", "scale", "width", "height", "png", "jpg"],
    component: lazy(() => import("@/tools/image/image-resizer")),
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress images with a quality slider and see before/after file sizes",
    category: "image",
    icon: "Minimize2",
    keywords: ["image", "compress", "optimize", "reduce", "size", "jpg", "quality"],
    component: lazy(() => import("@/tools/image/image-compressor")),
  },
  {
    id: "image-converter",
    name: "Image Converter",
    description: "Convert images between PNG, JPEG, and WebP formats with quality control",
    category: "image",
    icon: "ImageDown",
    keywords: ["image", "convert", "png", "jpg", "jpeg", "webp", "format"],
    component: lazy(() => import("@/tools/image/image-converter")),
  },
  {
    id: "image-color-picker",
    name: "Image Color Picker",
    description: "Click anywhere on an image to extract its exact HEX, RGB, and HSL color",
    category: "image",
    icon: "Pipette",
    keywords: ["image", "color", "pick", "hex", "rgb", "hsl", "eyedropper"],
    component: lazy(() => import("@/tools/image/image-color-picker")),
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    description: "Drag to select and crop any region of your image.",
    category: "image",
    icon: "Crop",
    keywords: ["crop", "image", "cut", "resize"],
    component: lazy(() => import("@/tools/image/image-cropper")),
  },
  {
    id: "image-watermark",
    name: "Watermark Adder",
    description: "Add a text watermark to any image with custom position and style.",
    category: "image",
    icon: "Stamp",
    keywords: ["watermark", "image", "copyright", "text"],
    component: lazy(() => import("@/tools/image/image-watermark")),
  },
  {
    id: "meme-generator",
    name: "Meme Generator",
    description: "Add classic top/bottom impact text to any image.",
    category: "image",
    icon: "Laugh",
    keywords: ["meme", "generator", "funny", "image"],
    component: lazy(() => import("@/tools/image/meme-generator")),
  },
  {
    id: "photo-filter",
    name: "Photo Filter Tool",
    description: "Apply instant filters and adjustments to your images.",
    category: "image",
    icon: "Figma",
    keywords: ["filter", "photo", "image", "adjust"],
    component: lazy(() => import("@/tools/image/photo-filter")),
  },

  // ── Calculators ──────────────────────────────────────────────────────────
  {
    id: "age-calculator",
    name: "Age Calculator",
    description: "Calculate your exact age and days until your next birthday.",
    category: "calculator",
    icon: "Calendar",
    keywords: ["age", "birthday", "calculate", "time"],
    component: lazy(() => import("@/tools/calculator/age-calculator")),
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index with metric or imperial units.",
    category: "calculator",
    icon: "Activity",
    keywords: ["bmi", "health", "weight", "calculate"],
    component: lazy(() => import("@/tools/calculator/bmi-calculator")),
  },
  {
    id: "days-until",
    name: "Days Until Calculator",
    description: "Find out how many days until (or since) any date.",
    category: "calculator",
    icon: "CalendarClock",
    keywords: ["days", "until", "since", "date"],
    component: lazy(() => import("@/tools/calculator/days-until")),
  },
  {
    id: "discount-calculator",
    name: "Discount Calculator",
    description: "Calculate sale price, savings amount, and final cost after discount.",
    category: "calculator",
    icon: "Tag",
    keywords: ["discount", "sale", "price", "savings"],
    component: lazy(() => import("@/tools/calculator/discount-calculator")),
  },
  {
    id: "loan-calculator",
    name: "Loan / EMI Calculator",
    description: "Calculate monthly EMI, total payment, and interest for any loan.",
    category: "calculator",
    icon: "Banknote",
    keywords: ["loan", "emi", "interest", "finance"],
    component: lazy(() => import("@/tools/calculator/loan-calculator")),
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, increases, decreases, and changes instantly.",
    category: "calculator",
    icon: "Percent",
    keywords: ["percentage", "math", "increase", "decrease"],
    component: lazy(() => import("@/tools/calculator/percentage-calculator")),
  },
  {
    id: "world-clock",
    name: "World Clock",
    description: "View the current time in major cities around the world — live updates.",
    category: "calculator",
    icon: "Globe",
    keywords: ["clock", "world", "time", "zone"],
    component: lazy(() => import("@/tools/calculator/world-clock")),
  },

  // ── Utility Tools ────────────────────────────────────────────────────────
  {
    id: "cron-builder",
    name: "Cron Expression Builder",
    description: "Build cron job schedules visually with human-readable descriptions",
    category: "utility",
    icon: "Timer",
    keywords: ["cron", "schedule", "job", "task", "linux", "unix", "automation"],
    component: lazy(() => import("@/tools/utility/cron-builder")),
  },
  {
    id: "roman-numeral",
    name: "Roman Numeral Converter",
    description: "Convert between Arabic numbers and Roman numerals (I–MMMCMXCIX)",
    category: "utility",
    icon: "Sigma",
    keywords: ["roman", "numeral", "convert", "number", "latin"],
    component: lazy(() => import("@/tools/utility/roman-numeral")),
  },
  {
    id: "browser-notepad",
    name: "Browser Notepad",
    description: "A simple, persistent notepad that saves automatically to your browser.",
    category: "utility",
    icon: "FileEdit",
    keywords: ["notepad", "notes", "browser", "save"],
    component: lazy(() => import("@/tools/utility/browser-notepad")),
  },
  {
    id: "coin-flipper",
    name: "Coin Flipper",
    description: "Flip a virtual coin and track heads vs tails statistics.",
    category: "utility",
    icon: "CircleDashed",
    keywords: ["coin", "flip", "random", "heads", "tails"],
    component: lazy(() => import("@/tools/utility/coin-flipper")),
  },
  {
    id: "countdown-timer",
    name: "Countdown Timer",
    description: "Set a custom countdown and get alerted when it reaches zero.",
    category: "utility",
    icon: "Hourglass",
    keywords: ["timer", "countdown", "alert", "time"],
    component: lazy(() => import("@/tools/utility/countdown-timer")),
  },
  {
    id: "dice-roller",
    name: "Dice Roller",
    description: "Roll any dice — d4, d6, d8, d10, d12, d20, or d100.",
    category: "utility",
    icon: "Dices",
    keywords: ["dice", "roll", "random", "dnd"],
    component: lazy(() => import("@/tools/utility/dice-roller")),
  },
  {
    id: "habit-tracker",
    name: "Habit Tracker",
    description: "Track your daily habits. Data saved locally in your browser.",
    category: "utility",
    icon: "CheckCircle2",
    keywords: ["habit", "tracker", "daily", "goals"],
    component: lazy(() => import("@/tools/utility/habit-tracker")),
  },
  {
    id: "metronome",
    name: "Metronome",
    description: "Keep perfect time with an audio metronome for practice.",
    category: "utility",
    icon: "Music",
    keywords: ["metronome", "tempo", "beat", "music"],
    component: lazy(() => import("@/tools/utility/metronome")),
  },
  {
    id: "online-signature-maker",
    name: "Online Signature Maker",
    description: "Draw your signature on the canvas and download as PNG.",
    category: "utility",
    icon: "PenTool",
    keywords: ["signature", "draw", "png", "sign"],
    component: lazy(() => import("@/tools/utility/online-signature-maker")),
  },
  {
    id: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "Focus with timed work/break intervals using the Pomodoro Technique.",
    category: "utility",
    icon: "TimerReset",
    keywords: ["pomodoro", "focus", "timer", "productivity"],
    component: lazy(() => import("@/tools/utility/pomodoro-timer")),
  },
  {
    id: "random-name-picker",
    name: "Random Name Picker",
    description: "Enter names and randomly select a winner. Great for giveaways and decisions.",
    category: "utility",
    icon: "UserCheck",
    keywords: ["random", "picker", "name", "winner"],
    component: lazy(() => import("@/tools/utility/random-name-picker")),
  },
  {
    id: "reaction-time-tester",
    name: "Reaction Time Tester",
    description: "Click as fast as you can when the screen turns green. Test your reflexes!",
    category: "utility",
    icon: "Zap",
    keywords: ["reaction", "time", "tester", "reflex"],
    component: lazy(() => import("@/tools/utility/reaction-time-tester")),
  },
  {
    id: "stopwatch",
    name: "Stopwatch",
    description: "Precision stopwatch with lap timing.",
    category: "utility",
    icon: "Stopwatch",
    keywords: ["stopwatch", "timer", "lap", "time"],
    component: lazy(() => import("@/tools/utility/stopwatch")),
  },
  {
    id: "todo-list",
    name: "To-Do List",
    description: "Manage your tasks. Data is saved locally in your browser.",
    category: "utility",
    icon: "ListChecks",
    keywords: ["todo", "list", "tasks", "manage"],
    component: lazy(() => import("@/tools/utility/todo-list")),
  },
  {
    id: "typing-speed-test",
    name: "Typing Speed Test",
    description: "Test your typing speed in WPM and accuracy.",
    category: "utility",
    icon: "Keyboard",
    keywords: ["typing", "speed", "test", "wpm"],
    component: lazy(() => import("@/tools/utility/typing-speed-test")),
  },
  {
    id: "wheel-of-names",
    name: "Wheel of Names",
    description: "Add names and spin the wheel to pick a random winner!",
    category: "utility",
    icon: "Disc",
    keywords: ["wheel", "names", "random", "spin"],
    component: lazy(() => import("@/tools/utility/wheel-of-names")),
  },
]

export function getToolById(id: string): ToolMeta | undefined {
  return tools.find((t) => t.id === id)
}

export function getToolsByCategory(category: Category): ToolMeta[] {
  return tools.filter((t) => t.category === category)
}
